### ISSUE TITLE
EFS volumes mounting and un-mounting from cell 

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry-incubator/efs-volume-release#5]
Hi ,

I have deployed CF v256 with diego and volume_services_enabled: true. 
- {name: 256, version: 0+dev.4}
- {name: diego, version: 1.12.0+dev.2}
- {name: garden-runc, version: 1.4.0+dev.2}
- {name: cflinuxfs2-rootfs , version: 1.60.0}
- {name: nfs-volume , version: 1.1.0+dev.1}
- {name: efs-volume , version:  0.1.0-beta.1+dev.1}

According to the documentation i am able to create an EFS successfully using below steps .
cf create-service-broker efsbroker <BROKER_USERNAME> <BROKER_PASSWORD> http://efsbroker.YOUR.DOMAIN.com
cf enable-service-access efs
cf create-service efs generalPurpose myVolume
cf services

Getting services in org Naresh / space NareshSpace as admin...
OK

name        service   plan             bound apps   last operation
myVolume    efs       generalPurpose                delete failed
myVolume2   efs       generalPurpose                delete failed
myVolume4   efs       generalPurpose                create failed
myVolume7   efs       generalPurpose                create succeeded
myVolume8   efs       generalPurpose   hello        create succeeded
myVolume9   efs       generalPurpose                create succeeded

When ever is try to execute  cf bind-service <cf app> < cf efs service>, the application doesn't start up .

Upon checking the logs for efs-driver i found below .
"timestamp":"1506998293.042803288","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.start","log_level":1,"data":{"opts":{"ip":"10.96.39.157"},"se
ssion":"4.2.1.1"}}
{"timestamp":"1506998293.042839527","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.mounting-volume","log_level":1,"data":{"id":"fs-87c087ce","mo
untpoint":"/var/vcap/data/volumes/efs/fs-87c087ce","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1"}}
{"timestamp":"1506998293.042862892","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.mount.start","log_level":1,"data":{"ip":"10.96.39.157","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.2","target":"/var/vcap/data/volumes/efs/fs-87c087ce"}}
{"timestamp":"1506998293.042937994","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.mount.invoking-command.start","log_level":1,"data":{"args":["-t","nfs4","-o","vers=4.0,rsize=1048576,wsize=1048576,hard,intr,timeo=600,retrans=2,actimeo=0","10.96.39.157:/","/var/vcap/data/volumes/efs/fs-87c087ce"],"executable":"mount","ip":"10.96.39.157","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.2.1","target":"/var/vcap/data/volumes/efs/fs-87c087ce"}}
{"timestamp":"1506998295.222597837","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.mount.invoking-command.end","log_level":1,"data":{"args":["-t","nfs4","-o","vers=4.0,rsize=1048576,wsize=1048576,hard,intr,timeo=600,retrans=2,actimeo=0","10.96.39.157:/","/var/vcap/data/volumes/efs/fs-87c087ce"],"executable":"mount","ip":"10.96.39.157","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.2.1","target":"/var/vcap/data/volumes/efs/fs-87c087ce"}}
{"timestamp":"1506998295.222667456","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.mount.end","log_level":1,"data":{"ip":"10.96.39.157","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.2","target":"/var/vcap/data/volumes/efs/fs-87c087ce"}}
{"timestamp":"1506998295.227848053","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.volume-mounted","log_level":1,"data":{"name":"fs-87c087ce","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1"}}
{"timestamp":"1506998295.227893829","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.unmount.start","log_level":1,"data":{"opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.3"}}
{"timestamp":"1506998295.228723288","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.unmount.unmount-volume-folder","log_level":1,"data":{"mountpath":"/var/vcap/data/volumes/efs/fs-87c087ce","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.3"}}
{"timestamp":"1506998295.228753090","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.unmount.invoking-command.start","log_level":1,"data":{"args":["/var/vcap/data/volumes/efs/fs-87c087ce"],"executable":"umount","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.3.1"}}
{"timestamp":"1506998295.234805346","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.unmount.invoking-command.end","log_level":1,"data":{"args":["/var/vcap/data/volumes/efs/fs-87c087ce"],"executable":"umount","opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.3.1"}}
{"timestamp":"1506998295.234872341","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.unmount.unmounted-volume","log_level":1,"data":{"opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.3"}}
{"timestamp":"1506998295.234901190","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.unmount.end","log_level":1,"data":{"opts":{"ip":"10.96.39.157"},"session":"4.2.1.1.3"}}
{"timestamp":"1506998295.234914303","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.with-cancel.open-perms.end","log_level":1,"data":{"opts":{"ip":"10.96.39.157"},"session":"4.2.1.1"}}
{"timestamp":"1506998295.234953642","source":"efs-driver-server","message":"efs-driver-server.server.handle-open-perms.end","log_level":1,"data":{"session":"4.2"}}

any guidance will be great .

**Comment by nsharmacovs** [comment]
also in BBS logs i see 
{"timestamp":"1507049467.306097507","source":"bbs","message":"bbs.request.fail-actual-lrp.starting","log_level":1,"data":{"actual_lrp_key":{"process_guid":"497f7d0e-7a79-4872-be11-3294788d894e-43a12acb-e852-49d2-9ab2-9eebc183cf84","index":0,"domain":"cf-apps"},"method":"POST","placement_error":"found no compatible cell with required volume drivers","request":"/v1/actual_lrps/fail","session":"23569.1"}}
{"timestamp":"1507049467.314919949","source":"bbs","message":"bbs.request.fail-actual-lrp.complete","log_level":1,"data":{"actual_lrp_key":{"process_guid":"497f7d0e-7a79-4872-be11-3294788d894e-43a12acb-e852-49d2-9ab2-9eebc183cf84","index":0,"domain":"cf-apps"},"method":"POST","placement_error":"found no compatible cell with required volume drivers","request":"/v1/actual_lrps/fail","session":"23569.1"}}

**Comment by julian-hj** [comment]
From what I can see in the logs, it does not appear that you have installed the efsdriver job on any diego cell.  The efsdriver log you posted is from the broker vm.

Did you update your runtime configuration and redeploy diego?
https://github.com/cloudfoundry-incubator/efs-volume-release#new-way-use-bosh-add-ons-with-filtering

**Comment by nsharmacovs** [comment]
HI Julian,

I have installed efsdriver with diego cell .. 

- name: naresh_diego_cell_z1
  instances: 1
  resource_pool: medium_z1
  templates:
  - {name: consul_agent, release: '256',consumes: {consul: nil}}
  - {name: rep, release: diego}
  - {name: garden, release: garden-runc}
  - {name: cflinuxfs2-rootfs-setup, release: cflinuxfs2-rootfs}
  - {name: metron_agent, release: '256'}
  - {name: nfsv3driver, release: "nfs-volume"}
  - {name: efsdriver, release: "efs-volume"}
  - {name: efsbroker,release: "efs-volume"}
  networks:
  - name: cf1_dyn
  properties:
    metron_agent: {zone: z1, deployment: '256'}
    networks: {apps: cf1_dyn}
    diego:
      rep:
        zone: z1
      executor:
        volman:
          driver_paths: /etc/docker/plugins
    route_registrar:
      routes:
      - name: efs-broker
        port: 8999
        registration_interval: 20s
        tags:
          component: efs-broker
        uris:
        - efs-broker.persi.cf-app.com
    consul:
      agent:
        services:

out put from diego cell 
naresh_diego_cell_z1/a6e1931d-f6ff-49aa-a784-6c0c01bd93e3:/var/vcap/jobs# ls -ltr
total 32
lrwxrwxrwx 1 root root 73 Oct  2 19:37 consul_agent -> /var/vcap/data/jobs/consul_agent/46f8ea6fa54bee1ec19352832046ccd366fc2d6c
lrwxrwxrwx 1 root root 64 Oct  2 19:38 rep -> /var/vcap/data/jobs/rep/40c389de9c91f2b88759dfb159c916b13e380ea9
lrwxrwxrwx 1 root root 67 Oct  2 19:38 garden -> /var/vcap/data/jobs/garden/323743b8e1f9987ad6b1c21a1d9265f9db917983
lrwxrwxrwx 1 root root 84 Oct  2 19:38 cflinuxfs2-rootfs-setup -> /var/vcap/data/jobs/cflinuxfs2-rootfs-setup/2f3c97cd63c41d162dfeab50430674b28c7a8779
lrwxrwxrwx 1 root root 73 Oct  2 19:38 metron_agent -> /var/vcap/data/jobs/metron_agent/62a388615cd59cf05af08d770ff8acb7a55e9839
lrwxrwxrwx 1 root root 72 Oct  2 19:38 nfsv3driver -> /var/vcap/data/jobs/nfsv3driver/f64eebaf6a815df3850ca434037e807f7515ab7e
lrwxrwxrwx 1 root root 70 Oct  2 19:38 efsdriver -> /var/vcap/data/jobs/efsdriver/51ee0d97ee4881cc6f195116d1d73c663c7c1ad3
lrwxrwxrwx 1 root root 70 Oct  2 19:38 efsbroker -> /var/vcap/data/jobs/efsbroker/09cddce1629ac15ef1dac08e5616d5d70faacd7a

**Comment by nsharmacovs** [comment]
please ignore my request looks like executor:volman:driver_paths: /etc/docker/plugins was the culprit .Its working for me now ..

**Comment by julian-hj** [comment]
👍
