### ISSUE TITLE
Question on efs service plan 

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry-incubator/efs-volume-release#6]
We register EFS broker by executing 
cf create-service-broker efsbroker <BROKER_USERNAME> <BROKER_PASSWORD> http://efsbroker.YOUR.DOMAIN.com
cf enable-service-access efs

Upon successful registration we can see the service plan by  executing 
$ cf marketplace -s efs
Getting service plan information for service efs as admin...
OK

service plan     description                                                                                                                                       free or paid
generalPurpose   recommended for most file systems                                                                                                                 free
maxIO            scales to higher levels of aggregate throughput and operations per second with a tradeoff of slightly higher latencies for most file operations   free

Also we are able to create volumes using below 
cf create-service efs generalPurpose myVolume

can we define the size for the volumes which is created by executing cf create-service or can we add a new service plans with different volume sizes ?

Regards,
Naresh Sharma

**Comment by julian-hj** [comment]
As far as I am aware, EFS does not support quotas for EFS volume sizes.  There is a quota for the number of EFS volumes you can use in an account, but not for the size limit on an individual EFS volume.

**Comment by julian-hj** [comment]
Closing this issue, as I believe it to be answered.  Please feel free to re-open it if you disagree.
